package javaswingdev.form;

import com.itextpdf.text.DocumentException;
import config.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author root
 */
public class Riwayat_Transaksi extends javax.swing.JFrame {
   
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabmodel;
    Connection cn = koneksi.getKoneksi();
    public Riwayat_Transaksi() {
        initComponents();
        tampil();
    }
    
    public void tampil(){
        try{
            Object[] baris = {"kode_transaksi", "total_bayar", "kembalian", "tanggal"};
            tabmodel = new DefaultTableModel(null, baris){
                  public boolean isCellEditable(int row, int column){
                return false;
                }
            };
            
            st = cn.createStatement();
            rs = st.executeQuery("select * from riwayat_transaksi");
            while (rs.next()){
                String kd = rs.getString("kode_transaksi");
                String ttl = rs.getString("total_bayar");
                String kbl = rs.getString("kembalian");
                java.util.Date tglDate = rs.getDate("tanggal_bayar");
                String tgl = new SimpleDateFormat("dd-MM-yyyy").format(tglDate);
                String[] row = {kd, ttl, kbl, tgl};
                tabmodel.addRow(row);
            }
            riwayattransaksi.setModel(tabmodel);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    // Metode untuk cetak struk ke PDF
    private void cetakStruk(String kodeTransaksi, String namaPelanggan, String totalBayar,String cash, String namaMenu, String kembalian, String tanggal) throws DocumentException {
        String folderPath = "src/Assets"; // Ganti dengan path relatif folder assets di dalam proyek Anda
        String filePath = folderPath + "StrukPembayaran_" + kodeTransaksi + ".pdf";
        StrukPrintable strukPembayaranPDF = new StrukPrintable(kodeTransaksi, namaPelanggan, totalBayar,cash, namaMenu, kembalian, tanggal);
        strukPembayaranPDF.generateStruk(filePath);

        JOptionPane.showMessageDialog(null, "Struk pembayaran telah dicetak dalam file PDF: " + filePath);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        riwayattransaksi = new javax.swing.JTable();
        cetak = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        kode_transaksi = new javax.swing.JTextField();
        Nama_pelanggan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        hapusTransaksi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        riwayattransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Transaksi", "Total", "Kembalian", "Tanggal"
            }
        ));
        riwayattransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayatMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(riwayattransaksi);

        cetak.setText("Cetak bukti pembayaran");
        cetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cetakMouseClicked(evt);
            }
        });
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Kode Transaksi");

        kode_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_transaksiActionPerformed(evt);
            }
        });

        Nama_pelanggan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Nama_pelangganFocusGained(evt);
            }
        });
        Nama_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama_pelangganActionPerformed(evt);
            }
        });
        Nama_pelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Nama_pelangganKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Nama_pelangganKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Nama_pelangganKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Atas Nama");

        hapusTransaksi.setText("HAPUS");
        hapusTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nama_pelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(kode_transaksi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hapusTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kode_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hapusTransaksi))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(cetak)
                .addGap(300, 300, 300))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void riwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatMouseClicked
        kode_transaksi.setText(tabmodel.getValueAt(riwayattransaksi.getSelectedRow(), 0).toString());        

    }//GEN-LAST:event_riwayatMouseClicked

    private void cetakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetakMouseClicked
        
    }//GEN-LAST:event_cetakMouseClicked

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here:
        int selectedRow = riwayattransaksi.getSelectedRow();
    if (selectedRow != -1) {
        String kodeTransaksi = tabmodel.getValueAt(selectedRow, 0).toString();
        String namaPelanggan = Nama_pelanggan.getText(); 
        String totalBayar = tabmodel.getValueAt(selectedRow, 1).toString();
//        String cash = tabmodel.getValueAt(selectedRow, 2).toString();
        String kembalian = tabmodel.getValueAt(selectedRow, 2).toString();
        String tanggal = tabmodel.getValueAt(selectedRow, 3).toString();
        String cash = getAdditionalDetailFromRiwayatTransaksi(kodeTransaksi);
        String namaMenu = getAdditionalMenuFromRiwayatTransaksi(kodeTransaksi);
            try {
                cetakStruk(kodeTransaksi, namaPelanggan, totalBayar,cash, namaMenu, kembalian, tanggal);
            } catch (DocumentException ex) {
                Logger.getLogger(Riwayat_Transaksi.class.getName()).log(Level.SEVERE, null, ex);
            }
    } else {
        JOptionPane.showMessageDialog(null, "Pilih transaksi terlebih dahulu.");
    }
    }//GEN-LAST:event_cetakActionPerformed
    
    private String getAdditionalDetailFromRiwayatTransaksi(String kodeTransaksi) {
    String cashFormatted = ""; 

    try {
        st = cn.createStatement();
        ResultSet resultSet = st.executeQuery("SELECT cash FROM riwayat_transaksi WHERE kode_transaksi = '" + kodeTransaksi + "'");

        if (resultSet.next()) {
            // Retrieve the cash value from the result set
            double cashValue = resultSet.getDouble("cash");
            
            // Format the cash value as currency
            cashFormatted = formatCurrency(cashValue);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error retrieving additional detail: " + e.getMessage());
    }

    return cashFormatted;
}
    private String getAdditionalMenuFromRiwayatTransaksi(String kodeTransaksi) {
    String menuDetail = ""; // Default value, adjust as needed

    try {
        st = cn.createStatement();
        ResultSet resultSet = st.executeQuery("SELECT nama_menu FROM riwayat_transaksi WHERE kode_transaksi = '" + kodeTransaksi + "'");

        if (resultSet.next()) {
            // Retrieve the cash value from the result set
            String namaMenu = resultSet.getString("nama_menu");
            
            // Format the cash value as currency
            menuDetail = namaMenu;
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error retrieving additional detail: " + e.getMessage());
    }

    return menuDetail;
}
    private String formatCurrency(double amount) {
    // Format the amount as currency in Indonesian Rupiah format
    Locale localeID = new Locale("id", "ID");
    NumberFormat currencyFormat = DecimalFormat.getCurrencyInstance(localeID);
    return currencyFormat.format(amount);
}
    
    private void kode_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_transaksiActionPerformed

    private void Nama_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nama_pelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nama_pelangganActionPerformed

    private void Nama_pelangganFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Nama_pelangganFocusGained

    }//GEN-LAST:event_Nama_pelangganFocusGained

    private void Nama_pelangganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nama_pelangganKeyPressed

    }//GEN-LAST:event_Nama_pelangganKeyPressed

    private void Nama_pelangganKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nama_pelangganKeyReleased
        
    }//GEN-LAST:event_Nama_pelangganKeyReleased

    private void Nama_pelangganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nama_pelangganKeyTyped
        char enter = evt.getKeyChar();
        if(Character.isDigit(enter)){
            evt.consume();
        }
    }//GEN-LAST:event_Nama_pelangganKeyTyped

    private void hapusTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusTransaksiActionPerformed
        // TODO add your handling code here:
        int ok= JOptionPane.showConfirmDialog(null,"Cius mau dihapus='"+
            kode_transaksi.getText()+"'","punten",JOptionPane.YES_NO_OPTION);
        if (ok==0) {
            try {
                PreparedStatement ps = cn.prepareStatement("DELETE FROM riwayat_transaksi WHERE kode_transaksi=?");
                ps.setString(1, kode_transaksi.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Riwayat Transaksi Telah Di Hapus");
                tampil();
            } catch (Exception e) {
                System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
            }
        }
    }//GEN-LAST:event_hapusTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Riwayat_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Riwayat_Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nama_pelanggan;
    private javax.swing.JButton cetak;
    private javax.swing.JButton hapusTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField kode_transaksi;
    private javax.swing.JTable riwayattransaksi;
    // End of variables declaration//GEN-END:variables
}
